notifications:
  email: false

language: generic

env:
  - DIST=CentOS
  - DIST=Ubuntu

before_script:
  - docker build -t ${tag=whatigot} -f "$DIST"/Dockerfile .

script:
  - out=$(docker run --rm $tag) &&
    sed q <<<"$out" | grep -F "$DIST" &&
    sed '2!d' <<<"$out" | grep -x =\*

  - sed 1,3d <<<"$out" | ./test
